
import { Template } from "@/types/designer";

export const defaultTemplates: Template[] = [
  {
    id: "employee-id",
    name: "Employee ID Card",
    thumbnail: "/templates/employee-id.png",
    width: 350,
    height: 500,
    elements: [
      {
        id: "background",
        type: "shape",
        position: { x: 0, y: 0, width: 350, height: 500, rotation: 0 },
        locked: false,
        layerIndex: 0,
        shape: "rectangle",
        backgroundColor: "#ffffff",
        borderColor: "#e0e0e0",
        borderWidth: 1,
        borderRadius: 10,
      },
      {
        id: "header",
        type: "shape",
        position: { x: 0, y: 0, width: 350, height: 100, rotation: 0 },
        locked: false,
        layerIndex: 1,
        shape: "rectangle",
        backgroundColor: "#0066ff",
        borderColor: "#0066ff",
        borderWidth: 0,
        borderRadius: 0,
      },
      {
        id: "company-name",
        type: "text",
        position: { x: 175, y: 50, width: 300, height: 40, rotation: 0 },
        locked: false,
        layerIndex: 2,
        text: "COMPANY NAME",
        fontSize: 24,
        fontFamily: "Inter",
        color: "#ffffff",
        fontWeight: "bold",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
      },
      {
        id: "photo-placeholder",
        type: "shape",
        position: { x: 125, y: 150, width: 100, height: 100, rotation: 0 },
        locked: false,
        layerIndex: 3,
        shape: "rectangle",
        backgroundColor: "#f0f0f0",
        borderColor: "#e0e0e0",
        borderWidth: 1,
        borderRadius: 50,
      },
      {
        id: "name-label",
        type: "text",
        position: { x: 175, y: 280, width: 300, height: 30, rotation: 0 },
        locked: false,
        layerIndex: 4,
        text: "John Doe",
        fontSize: 18,
        fontFamily: "Inter",
        color: "#333333",
        fontWeight: "bold",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
      },
      {
        id: "position-label",
        type: "text",
        position: { x: 175, y: 310, width: 300, height: 30, rotation: 0 },
        locked: false,
        layerIndex: 5,
        text: "Software Engineer",
        fontSize: 14,
        fontFamily: "Inter",
        color: "#666666",
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
      },
      {
        id: "id-number",
        type: "text",
        position: { x: 175, y: 370, width: 300, height: 30, rotation: 0 },
        locked: false,
        layerIndex: 6,
        text: "ID: EMP-12345",
        fontSize: 14,
        fontFamily: "Inter",
        color: "#333333",
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
      },
      {
        id: "footer",
        type: "shape",
        position: { x: 0, y: 450, width: 350, height: 50, rotation: 0 },
        locked: false,
        layerIndex: 7,
        shape: "rectangle",
        backgroundColor: "#0066ff",
        borderColor: "#0066ff",
        borderWidth: 0,
        borderRadius: 0,
      },
    ],
  },
  {
    id: "student-id",
    name: "Student ID Card",
    thumbnail: "/templates/student-id.png",
    width: 350,
    height: 500,
    elements: [
      {
        id: "background",
        type: "shape",
        position: { x: 0, y: 0, width: 350, height: 500, rotation: 0 },
        locked: false,
        layerIndex: 0,
        shape: "rectangle",
        backgroundColor: "#ffffff",
        borderColor: "#e0e0e0",
        borderWidth: 1,
        borderRadius: 10,
      },
      {
        id: "header",
        type: "shape",
        position: { x: 0, y: 0, width: 350, height: 100, rotation: 0 },
        locked: false,
        layerIndex: 1,
        shape: "rectangle",
        backgroundColor: "#2E3192",
        borderColor: "#2E3192",
        borderWidth: 0,
        borderRadius: 0,
      },
      {
        id: "school-name",
        type: "text",
        position: { x: 175, y: 50, width: 300, height: 40, rotation: 0 },
        locked: false,
        layerIndex: 2,
        text: "UNIVERSITY",
        fontSize: 24,
        fontFamily: "Inter",
        color: "#ffffff",
        fontWeight: "bold",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
      },
      {
        id: "photo-placeholder",
        type: "shape",
        position: { x: 125, y: 150, width: 100, height: 100, rotation: 0 },
        locked: false,
        layerIndex: 3,
        shape: "rectangle",
        backgroundColor: "#f0f0f0",
        borderColor: "#e0e0e0",
        borderWidth: 1,
        borderRadius: 50,
      },
      {
        id: "name-label",
        type: "text",
        position: { x: 175, y: 280, width: 300, height: 30, rotation: 0 },
        locked: false,
        layerIndex: 4,
        text: "Jane Smith",
        fontSize: 18,
        fontFamily: "Inter",
        color: "#333333",
        fontWeight: "bold",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
      },
      {
        id: "department-label",
        type: "text",
        position: { x: 175, y: 310, width: 300, height: 30, rotation: 0 },
        locked: false,
        layerIndex: 5,
        text: "Computer Science",
        fontSize: 14,
        fontFamily: "Inter",
        color: "#666666",
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
      },
      {
        id: "student-id",
        type: "text",
        position: { x: 175, y: 370, width: 300, height: 30, rotation: 0 },
        locked: false,
        layerIndex: 6,
        text: "Student ID: 2023001",
        fontSize: 14,
        fontFamily: "Inter",
        color: "#333333",
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
      },
      {
        id: "expiry-date",
        type: "text",
        position: { x: 175, y: 400, width: 300, height: 30, rotation: 0 },
        locked: false,
        layerIndex: 7,
        text: "Valid until: 12/31/2023",
        fontSize: 12,
        fontFamily: "Inter",
        color: "#666666",
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
      },
      {
        id: "footer",
        type: "shape",
        position: { x: 0, y: 450, width: 350, height: 50, rotation: 0 },
        locked: false,
        layerIndex: 8,
        shape: "rectangle",
        backgroundColor: "#2E3192",
        borderColor: "#2E3192",
        borderWidth: 0,
        borderRadius: 0,
      },
    ],
  },
  {
    id: "blank-card",
    name: "Blank Card",
    thumbnail: "/templates/blank-card.png",
    width: 350,
    height: 500,
    elements: [
      {
        id: "background",
        type: "shape",
        position: { x: 0, y: 0, width: 350, height: 500, rotation: 0 },
        locked: false,
        layerIndex: 0,
        shape: "rectangle",
        backgroundColor: "#ffffff",
        borderColor: "#e0e0e0",
        borderWidth: 1,
        borderRadius: 10,
      },
    ],
  },
];
